"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Login } from "@/Login";
import { appStore } from "../redux/appStore";
import { Provider, useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function LayoutWrapper({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dispatch = useDispatch();
  const isLoggedIn = useSelector((state: any) => {
    return state?.appReducer?.isLoggedIn;
  });
  const user = useSelector((state: any) => {
    return state?.appReducer?.user;
  });

  const handleLogout = () => {
    const bool = confirm("Are you sure, you want to Logout!!");
    if (bool) {
      sessionStorage.clear();
      dispatch({ type: "LOGIN", payload: { isLoggedIn: false, user: "" } });
    }
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={appStore}>
          {isLoggedIn ? (
            <div>
              <h3>{user}</h3>
              <button onClick={handleLogout}>Logout</button>
              {children}
            </div>
          ) : (
            <Login />
          )}
        </Provider>
      </body>
    </html>
  );
}
